# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false 


format = """
[ ](#6a9589)\
$directory\
[](bg:green fg:#6a9589)\
$git_branch\
$git_status\
[](bg:#2a2a37 fg:green)\
$time\
[ ](fg:#2a2a37)\
"""

[directory]
style="bg:#6a9589 fg:black"
format = "[ $path ]($style)"
truncation_length = 2 
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:green fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:black"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2a2a37 fg:white"
format = '[  $time ]($style)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
