export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster"
zstyle ':omz:update' mode auto      # update automatically without asking
zstyle ':omz:update' frequency 13

# Plugins
plugins=(git zsh-autosuggestions zsh-syntax-highlighting zsh-autocomplete eza tmux fzf )
ZSH_TMUX_DEFAULT_SESSION_NAME="master"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_UNICODE=true

# Variables
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin/
export XDG_CONFIG_HOME="$HOME/.config"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# Alias
alias vim="nvim"
alias vi="nvim"
alias src="source ~/.zshrc"
alias tree="eza --icons --tree"
alias cat='bat --paging=never'
alias lg='lazygit'

## FZF
export FZF_DEFAULT_OPTS="
  --tmux=center,90%,90%
  --bind 'ctrl-/:change-preview-window(down|hidden|)'
  --preview-window=right:60%
  --walker-skip=.git*,node_modules
"

# Preview file in file preview
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
"

# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window
export FZF_ALT_C_OPTS="
  --preview 'eza --icons --tree --color=always {}'
"

export FZF_DEFAULT_COMMAND='fd '
export FZF_CTRL_T_COMMAND='fd --type f'
export FZF_ALT_C_COMMAND='fd --type d --hidden'

source $ZSH/oh-my-zsh.sh
eval "$(starship init zsh)"
