ZSH_CONFIG_DIR="$HOME/.config/zsh"

ZSH_TMUX_DEFAULT_SESSION_NAME="master"
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_UNICODE=true
setopt HIST_SAVE_NO_DUPS
setopt interactivecomments

# Variables
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$(go env GOPATH)/bin/
export XDG_CONFIG_HOME="$HOME/.config"
export STARSHIP_CONFIG=~/.config/starship/starship.toml

# MacOS C Lib errors
if [[ "$(uname)" == "Darwin" ]]; then
    export PATH=/Library/Developer/CommandLineTools/usr/bin:$PATH
    export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
fi

# Colima Docker Engine Fix Testcontainers
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
export DOCKER_HOST="unix://${HOME}/.config/colima/docker.sock"


# # Lazygit switch dir on exit
lg()
{
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

    lazygit "$@"

    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
            cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
            rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}

## FZF
export FZF_DEFAULT_OPTS="
  --tmux=center,90%,90%
  --bind 'ctrl-/:change-preview-window(down|hidden|)'
  --preview-window=right:60%
  --walker-skip=.git,node_modules
"
export FZF_DEFAULT_COMMAND='fd '


# Preview file in file preview
export FZF_CTRL_T_OPTS="
  --preview 'bat -n --color=always {}'
"
export FZF_CTRL_T_COMMAND='fd --type f'

# CTRL-Y to copy the command into clipboard using pbcopy
export FZF_CTRL_R_OPTS="
  --bind 'ctrl-y:execute-silent(echo -n {2..} | pbcopy)+abort'
  --color header:italic
  --header 'Press CTRL-Y to copy command into clipboard'"

# Print tree structure in the preview window
export FZF_ALT_C_OPTS="
  --preview 'eza --icons --tree --color=always {}'
"
export FZF_ALT_C_COMMAND='fd --type d --hidden'


source ~/.nix-profile/share/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle eza
antigen bundle command-not-found
antigen bundle git
antigen bundle tmux
antigen bundle kubectl
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle marlonrichert/zsh-autocomplete@main
antigen apply

eval "$(starship init zsh)"
eval "$(zoxide init --cmd cd zsh)"
source <(fzf --zsh)
source <(kubectl completion zsh)
