# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false 

format = """
$directory\
[](fg:bright-green bg:green)\
$git_branch\
$git_status\
[](bg:background fg:green)\
$time\
"""

[directory]
style="bg:bright-green fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:green fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:green fg:black"
format = '[$all_status$ahead_behind ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:background fg:white"
format = '[  $time ]($style)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
